#!/usr/bin/env bash
PROJECT_DOCKER_REGISTRY_HOST=${PROJECT_DOCKER_REGISTRY_HOST:-""}
PROJECT_DOCKER_REGISTRY_PORT=${PROJECT_DOCKER_REGISTRY_PORT:-""}
PROJECT_DOCKER_REPOSITORY=${PROJECT_DOCKER_REPOSITORY:-"andrewjdawes/github-actions-docker"}
PROJECT_DOCKER_TAG=${PROJECT_DOCKER_TAG:-"latest"}
PROJECT_DOCKER_CONTAINER_NAME=${PROJECT_DOCKER_CONTAINER_NAME:-"github-actions-docker"}
